# --- General options --- #


# Name of website
title: AWS Cloud-Beratung und DevOps-Expertiese | Elastic2ls Bonn

# Short description of your site
description: Elastic2ls ist ein Startup Unternehmen aus Bonn. Wir unterstützen Sie mit unserer Expertise bei der Cloud-Tranformationen und DevOps.


# url is the the website domain URL without a trailing slash
url: "https://www.elastic2ls.com"

# website logo
title-img: "/img/Logo_box-1-150x150.webp"

# website author
author:
  name: Alexander Wiechert

# baseurl should be an empty string
baseurl: ""

#pwa settings
name: "elastic[too]ls.com"
short_name: "elastic2ls"
orientation: "any"
lang: "German"
color: ""#18BC9C"

# --- Web Statistics Section --- #
# Fill in your Google Analytics gtag.js ID to track your website using gtag
gtag: "UA-85377423-1"

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: "UA-85377423-1"

# Google Tag Manager ID
gtm: "GTM-P7RZL44"

# --- Misc --- #
# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format
date_format: "%B %-d, %Y"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Berlin"
markdown: kramdown
permalink: /:year-:month-:day-:title/
#paginate: 5

kramdown:
  syntax_highlighter: rouge


# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

plugins:
#  - jekyll-minifier
  - jekyll-feed
  - jekyll-readme-index
  - jekyll-include-cache
  - jekyll-sitemap
sass:
  style: compressed



# assets:
#   compress:
#     css: true
#     js: true

#jekyll-minifier:
#  preserve_php: true                # Default: false
#  remove_spaces_inside_tags: true   # Default: true
#  remove_multi_spaces: true         # Default: true
#  remove_comments: true             # Default: true
#  remove_intertag_spaces: true      # Default: false
#  remove_quotes: false              # Default: false
#  compress_css: true                # Default: true
#  compress_javascript: true         # Default: true
#  compress_json: true               # Default: true
#  simple_doctype: false             # Default: false
#  remove_script_attributes: false   # Default: false
#  remove_style_attributes: false    # Default: false
#  remove_link_attributes: false     # Default: false
#  remove_form_attributes: false     # Default: false
#  remove_input_attributes: false    # Default: false
#  remove_javascript_protocol: false # Default: false
#  remove_http_protocol: false       # Default: false
#  remove_https_protocol: false      # Default: false
#  preserve_line_breaks: false       # Default: false
#  simple_boolean_attributes: false  # Default: false
#  compress_js_templates: false      # Default: false
#  preserve_patterns:                # Default: (empty)
#  uglifier_args:                    # Default: (empty)
#  uglifier_args:
#     harmony: true
#
#compress_images:
#  images_path: "img/**/*.{gif.webp,jpg,jpeg,svg}"

collections:
  blog:
    output: true